services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - ngoclam-zmp-be

  ngoclam-zmp-be:
    image: truonghx/ngoclam-be:b66cb5a
    container_name: ngoclam-zmp-be
    ports:
      - "8080:8080"
    volumes:
      - ./api.env:/app/.env
    env_file:
      - ./api.env
    restart: always
